[env:esp32-c6-devkitm-1]
; officiele espressif32-platform mist arduino-framework support voor C6-boards -> pioarduino fork
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.39/platform-espressif32.zip
board = esp32-c6-devkitm-1
framework = arduino

upload_port = COM10
monitor_port = COM10
monitor_speed = 115200

build_flags =
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1   ; C6 heeft USB-Serial/JTAG (geen native USB-OTG zoals S2/S3) -> HW CDC mode

lib_deps =
    h2zero/NimBLE-Arduino @ ^2.5.0
    olikraus/U8g2 @ ^2.35.19
